### ISSUE TITLE
项目求助

### ISSUE THREAD

**Issue by summer1127** [ruisizhang123/REMARK-LLM#2]
学姐很抱歉又来打扰您，之前的问题是因为中国大陆网络的问题导致t5无法加载，加上VPN之后解决了这个问题，但是目前我遇到了新的问题
![image](https://github.com/user-attachments/assets/c436c35d-9d77-4abd-b22e-dc73743c5a81)
transformers.models.bert 模块缺少 BertTokenizerFast 类。这个问题需要如何解决呢呜呜呜

**Comment by ruisizhang123** [comment]
Seems to be some package version incompatibility.
The `pip install evaluate==0.4.2` works in my end.

**Comment by 18handbag** [comment]
请问问题解决了吗
