### ISSUE TITLE
有关“./nlp_dataset/ChatGPT-Research-Abstracts/index_train.txt",文件的问题

### ISSUE THREAD

**Issue by LliminM** [ruisizhang123/REMARK-LLM#4]
我已经训练完了模型，现在想要验证模型的功能，可是我注意到inference.py中需要用到"./nlp_dataset/ChatGPT-Research-Abstracts/index_train.txt"这个文件，但是github中好像并没有提供，如何获得该文件呢？

**Comment by ruisizhang123** [comment]
It's saved during training [here](https://github.com/ruisizhang123/REMARK-LLM/blob/777ccb3b67fb937c276431fa3bd980813b641a21/utils.py#L38)
